version: '2.7'

services:
  web:
    build: ./
    command: gunicorn tracker.wsgi:application -b 0.0.0.0:8000 --reload
    volumes:
      - ./:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: mysql:5.7
    volumes:
      - mysql_data:/var/mysql/
      - ./db-dump:/docker-entrypoint-initdb.d
    env_file:
      - ./.env.db
  nginx:
    restart: always
    image: nginx
    expose:
      - 8000
    ports:
    - 80:8000
    volumes:
      - ./tracker/static:/usr/src/app/tracker/static
      - ./tracker/media:/usr/src/app/tracker/media
      - ./logs:/usr/src/app/logs
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - db
      - web


volumes:
    mysql_data: