version: '3'

services:
  web:
    build: ./
    volumes:
      - ./:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db
      - redis
  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    command: --wait-timeout=28800
    volumes:
      - mysql_data:/var/mysql/
    env_file:
      - ./.env.db
  nginx:
    restart: always
    image: nginx
    expose:
      - 8000
    ports:
      - 80:8000
    volumes:
      - ./tracker/static:/usr/src/app/tracker/static
      - ./tracker/media:/usr/src/app/tracker/media
      - ./logs:/usr/src/app/logs
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - db
      - web
  redis:
    image: redis
    ports:
      - 6379:6379
    depends_on:
      - db


volumes:
    mysql_data:
